### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by nmskhan** [cookpa/antsInstallExample#1]
Hi
I have used this downloadable script (https://github.com/cookpa/antsInstallExample) to install the ANTS in my local folder. Everything has been installed. it creates three directories, like ANTs, build and install in /Users/Macuser/Documents/. I do not see any antsbins or bins directories in ANTs or build directory and I do see bin directory in the install folder. Unfortunately, I tried to set the environment variable to the scripts folder in ANTs directory, it does not work.
export ANTSPATH=/Users/Macuser/Documents/ANTs/Scripts/
export=PATH=${ANTSPATH}:$PATH
Still, the antsRegistrationSyN.sh command not found. Any fixes for this? or I am doing wrong?
I tried installing in multiple places but in vain.
Please let me know Thanks
Ned

**Comment by cookpa** [comment]
The binaries and scripts should be installed under `install/bin/`. You would want to set ANTSPATH and PATH to point to that directory.

**Comment by nmskhan** [comment]
thanks for a quick reply. I will try that and will let you know. 
Thanks
Ned

**Comment by nmskhan** [comment]
Thanks, it worked.
