### ISSUE TITLE
Execute Process Error

### ISSUE THREAD

**Issue by son520804** [cookpa/antsInstallExample#2]
When I run the line 65: make -j $buildThreads 2>&1 | tee build.log

The build.log file returns the following error message:
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (execute_process):
  execute_process given unknown argument "-".

make[3]: *** [install] Error 1
make[2]: *** [ITKv5-prefix/src/ITKv5-stamp/ITKv5-install] Error 2
make[1]: *** [CMakeFiles/ITKv5.dir/all] Error 2
make: *** [all] Error 2

Questions:
1. Where did the unknown argument "-" specify?
2. The reproducible step for this error is to run the bash script installing ANTs. How to resolve this issue?
Thank you so much!

**Comment by cookpa** [comment]
I've never seen this before. Can you upload build.log?
